name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: latest

      - name: Check Formatting
        run: zig fmt --ast-check --check .

      - name: Build (windows-x86_64)
        run: zig build -Dtarget=x86_64-windows-gnu -Denable_cli

      - name: Build (windows-aarch64)
        run: zig build -Dtarget=aarch64-windows-gnu -Denable_cli

      - name: Build (windows-x86)
        run: zig build -Dtarget=x86-windows-gnu -Denable_cli

      - name: Build (macos-x86_64)
        run: zig build -Dtarget=x86_64-macos-none -Denable_cli

      - name: Build (macos-aarch64)
        run: zig build -Dtarget=aarch64-macos-none -Denable_cli

      - name: Build (linux-x86_64)
        run: zig build -Dtarget=x86_64-linux-musl -Denable_cli

      - name: Build (linux-aarch64)
        run: zig build -Dtarget=aarch64-linux-musl -Denable_cli

      - name: Build (linux-arm)
        run: zig build -Dtarget=arm-linux-musleabihf -Denable_cli

      - name: Build (linux-riscv64)
        run: zig build -Dtarget=riscv64-linux-musl -Denable_cli

      - name: Build (linux-powerpc64le)
        run: zig build -Dtarget=powerpc64le-linux-musl -Denable_cli

      - name: Build (linux-x86)
        run: zig build -Dtarget=x86-linux-musl -Denable_cli

      - name: Build (linux-loongarch64)
        run: zig build -Dtarget=loongarch64-linux-musl -Denable_cli

      - name: Build (linux-s390x)
        run: zig build -Dtarget=s390x-linux-musl -Denable_cli

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: latest

      - name: Test
        run: zig build test -Denable_cli

      - name: Test (sanitize_thread)
        if: matrix.os != 'windows-latest'
        run: zig build test -Denable_cli -Dsanitize_thread
